### ISSUE TITLE
Bug Report: sca.py wipes FW of all FPGA's regardless of link Mask

### ISSUE THREAD

**Issue by bdorney** [evka85/GEM_AMC#19]
When programming OHv3b from CTP7 I noticed the following:

```
eagle60:~/apps/reg_interface$ python sca.py 0x1 program-fpga bit ~/oh_fw/OH-20180223-3.0.10.A.bit
```

This will program FW of link 0 but wipes FW of link 1.

```
eagle60:~/apps/reg_interface$ python sca.py 0x2 program-fpga bit ~/oh_fw/OH-20180223-3.0.10.A.bit
```

Programs FW of link 1 but wipes FW of link 0.

```
eagle60:~/apps/reg_interface$ python sca.py 0x3 program-fpga bit ~/oh_fw/OH-20180223-3.0.10.A.bit
```

Will wipe FW and program FPGA's of both link 0 and 1.

I would have expected the wiping of the FPGA firmware to follow the oh mask, e.g. if a link is not included the FW will *not* be wiped.

@evka85 @mexanick @jsturdy @andrewpeck

**Comment by evka85** [comment]
Hi Brian,

I reviewed the sca.py code and I do not see an obvious way of how that would happen.. Are you sure that you are not executing SCA reset (sca.py <link_mask> r) in between these calls? SCA reset reconfigures all SCAs which results in an OH FPGA hard-reset, so that would wipe out firmware on all links.

If you're not executing an SCA reset, then I'd need to test this out and debug in more detail.

Cheers,
Evaldas

**Comment by bdorney** [comment]
> Are you sure that you are not executing SCA reset (sca.py <link_mask> r) in between these calls? SCA reset reconfigures all SCAs which results in an OH FPGA hard-reset, so that would wipe out firmware on all links.

I am certain the exact commands above were executed and no other commands, e.g. no sca reset, were issued in between calls shown above.

**Comment by bdorney** [comment]
It seems I was mistaken, on further testing when programming the FPGA the `OH_MASK` is respected however when reseting the SCA it is not:

http://cmsonline.cern.ch/cms-elog/1031655

This might also be an issue in `xhal` and this is probably why these two scripts should probably be standardized. @evka85 @mexanick.

**Comment by bdorney** [comment]
This was resolved by the addition of the SCA RESET ENABLE mask register.
