### ISSUE TITLE
[Version 3.7.0] Address tables only contain 12OH's

### ISSUE THREAD

**Issue by lpetre-ulb** [evka85/GEM_AMC#26]
When testing the new CTP7 firmware release (3.7.0), I noticed that the address tables present [with the bitfile release](https://github.com/evka85/GEM_AMC/releases/tag/v3.7.0) do not contain the 12OH's, but only 4.

This can also be seen in the repository code :
https://github.com/evka85/GEM_AMC/blob/2c7c6b8c679bd60485e22100204ec1055fe699fc/scripts/address_table/gem_amc_top.xml#L1283-L1285

After correcting the "new address table", as it is named is the archive, I was able to communicate with the 12OH's with the `gem_reg.py` tool.

**Comment by evka85** [comment]
fixed
