### ISSUE TITLE
[Version 3.7.0] Trigger links are always reported in an healthy state

### ISSUE THREAD

**Issue by lpetre-ulb** [evka85/GEM_AMC#27]
When testing the new CTP7 firmware release (3.7.0), I noticed that the trigger links are always reported in an healthy state even if the fibers are not connected or the OH FPGA is not programmed.

In the following case, none of the OH10 fibers were connected :
``` bash
eagle63 > write GEM_AMC.TRIGGER.CTRL.CNT_RESET  1
Initial value to write: 1, register GEM_AMC.TRIGGER.CTRL.CNT_RESET
0x00000001(1)   written to GEM_AMC.TRIGGER.CTRL.CNT_RESET
eagle63 > kw GEM_AMC.TRIGGER.OH10.LINK
0x66002e80 r    GEM_AMC.TRIGGER.OH10.LINK0_SBIT_OVERFLOW_CNT        0x00000000
0x66002e80 r    GEM_AMC.TRIGGER.OH10.LINK1_SBIT_OVERFLOW_CNT        0x00000000
0x66002e84 r    GEM_AMC.TRIGGER.OH10.LINK0_MISSED_COMMA_CNT     0x00000000
0x66002e84 r    GEM_AMC.TRIGGER.OH10.LINK1_MISSED_COMMA_CNT     0x00000000
0x66002e8c r    GEM_AMC.TRIGGER.OH10.LINK0_OVERFLOW_CNT         0x00000000
0x66002e8c r    GEM_AMC.TRIGGER.OH10.LINK1_OVERFLOW_CNT         0x00000000
0x66002e90 r    GEM_AMC.TRIGGER.OH10.LINK0_UNDERFLOW_CNT        0x00000000
0x66002e90 r    GEM_AMC.TRIGGER.OH10.LINK1_UNDERFLOW_CNT        0x00000000
0x66002e94 r    GEM_AMC.TRIGGER.OH10.LINK0_SYNC_WORD_CNT        0x00000000
0x66002e94 r    GEM_AMC.TRIGGER.OH10.LINK1_SYNC_WORD_CNT        0x00000000
```

I'll test test if the trigger data content is correctly received, but the status seems wrong. Yet, I would have expected that some of the error counters increase when the trigger links are not connected or the OH FPGA is not programmed.

**Comment by evka85** [comment]
Hi Laurent,

Fixed in v3.7.2.
There were some system registers missing in the firmware that are needed to configure the miniPOD links correctly on startup (which is done by the cold_boot.sh script, but it could only talk to the CXP links).

Thanks for reporting!
