### ISSUE TITLE
Potential Bug When Writing GEM_AMC.SLOW_CONTROL.SCA.CTRL.TTC_HARD_RESET_EN Post 3.8.4??

### ISSUE THREAD

**Issue by bdorney** [evka85/GEM_AMC#40]
Looking at the release notes for [3.8.4](https://github.com/evka85/GEM_AMC/releases/tag/v3.8.4) I see that:

> SCA TTC_HARD_RESET_EN is now an OH mask instead of just one bit

If I call `recover.sh` on the card I get the following error:

```bash
Set ignore TTC hard resets
reg_interface.py -e write GEM_AMC.SLOW_CONTROL.SCA.CTRL.TTC_HARD_RESET_EN 0
Extended prompt module found
Open pickled address table if available  /mnt/persistent/gemdaq/xml/gem_amc_top.pickle...
Initial value to write: 0, register GEM_AMC.SLOW_CONTROL.SCA.CTRL.TTC_HARD_RESET_EN
Writing masked reg GEM_AMC.SLOW_CONTROL.SCA.CTRL.TTC_HARD_RESET_EN failed. Exiting...
wReg output -2
0xfffffffe(0)	written to GEM_AMC.SLOW_CONTROL.SCA.CTRL.TTC_HARD_RESET_EN
```

Then trying to write it manually from reg_interface.py on the card unsurprisingly fails:

```
eagle26:/mnt/persistent/gemdaq$ reg_interface.py
Extended prompt module found
Open pickled address table if available  /mnt/persistent/gemdaq/xml/gem_amc_top.pickle...
Starting CTP7 Register Command Line Interface. Please connect to CTP7 using connect <hostname> command unless you use it directly at the CTP7
CTP7 > doc GEM_AMC.SLOW_CONTROL.SCA.CTRL.TTC_HARD_RESET_EN
Name: GEM_AMC.SLOW_CONTROL.SCA.CTRL.TTC_HARD_RESET_EN
Description: When this is set to 1 (default), TTC hard reset commands are forwarded to the SCA to reset the OH FPGA
Address: 0x00b00002
Permission: rw
Mask: 0x00000001
Module: False
Parent: GEM_AMC.SLOW_CONTROL.SCA.CTRL
None
CTP7 > write GEM_AMC.SLOW_CONTROL.SCA.CTRL.TTC_HARD_RESET_EN 0
Initial value to write: 0, register GEM_AMC.SLOW_CONTROL.SCA.CTRL.TTC_HARD_RESET_EN
Writing masked reg GEM_AMC.SLOW_CONTROL.SCA.CTRL.TTC_HARD_RESET_EN failed. Exiting...
wReg output -2
0xfffffffe(0)	written to GEM_AMC.SLOW_CONTROL.SCA.CTRL.TTC_HARD_RESET_EN
```

Moreover the register documentation does not match the fact that this is now a 12-bit register. 

Perhaps this is due to an outdated pickle file?  I will try this from the DAQ machine once I have finished my FW update.

@mexanick @jsturdy @evka85  

For the record I'm using GEM_AMC [3.8.6](https://github.com/evka85/GEM_AMC/releases/tag/v3.8.6)

**Comment by bdorney** [comment]
This does appear to be a problem with the pickle file on the card:

```
[gemuser@gem904qc8daq address_table_v3_8_6_12oh]$ gem_reg.py
Open pickled address table if available  /opt/cmsgemos/etc/maps//amc_address_table_top.pickle...
Pickle file not found, parsing  /opt/cmsgemos/etc/maps//amc_address_table_top.xml ...
Starting CTP7 Register Command Line Interface. Please connect to CTP7 using connect <hostname> command unless you use it directly at the CTP7
CTP7 > connect gem.shelf01.amc02
gem.shelf01.amc02 > doc GEM_AMC.SLOW_CONTROL.SCA.CTRL.TTC_HARD_RESET_EN
Name: GEM_AMC.SLOW_CONTROL.SCA.CTRL.TTC_HARD_RESET_EN
Description: This is a bitmask (one bit per OH) that determines whether or not TTC hard reset commands are forwarded to the SCA to reset the OH FPGA
Address: 0x00b00002
Permission: rw
Mask: None
Module: False
Parent: GEM_AMC.SLOW_CONTROL.SCA.CTRL
None
gem.shelf01.amc02 > write GEM_AMC.SLOW_CONTROL.SCA.CTRL.TTC_HARD_RESET_EN 0x0
Initial value to write: 0, register GEM_AMC.SLOW_CONTROL.SCA.CTRL.TTC_HARD_RESET_EN
0x00000000(0)	written to GEM_AMC.SLOW_CONTROL.SCA.CTRL.TTC_HARD_RESET_EN
```

So this is probably another good time to point out that we need to resolve the issues with this pickle file (e.g. how it's memory balloons beyond what the Zynq RAM has available with 12 OH's, and that the version on the DAQ machine cannot be seamlessly used on the card and needs to be manually edited).

**Comment by bdorney** [comment]
@evka85 from the register documentation it's not apparent whether 0xfff means "forward TTC hard resets to all links" or "all links will not receive TTC hard resets."  Could you clarify this here and also in the xml documentation what a value of 1 in the N^th bit stands for?

**Comment by evka85** [comment]
Ok sure, I've clarified that in my local copy of the XML  (Nth bit set to 1 will enable TTC hard resets to the Nth OH), and will commit this with the next push (this will be coupled with the calibration data format).
I agree that the rw_reg memory problem should be addressed, we should follow that up with Misha, this could be a good task for one of the students.
